# Generated by Django 2.2 on 2022-08-14 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api_app', '0002_db_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='DB_project_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='--', max_length=50, null=True)),
                ('des', models.CharField(blank=True, default='--', max_length=500, null=True)),
                ('creater', models.IntegerField(default=0)),
            ],
        ),
    ]
