# Generated by Django 2.2 on 2022-08-14 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api_app', '0003_db_project_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='db_project_list',
            name='operate',
            field=models.IntegerField(default=0),
        ),
    ]
