# Generated by Django 2.2 on 2022-08-14 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api_app', '0004_db_project_list_operate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='db_project_list',
            name='operate',
        ),
    ]
