# Generated by Django 2.2 on 2022-08-23 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api_app', '0005_remove_db_project_list_operate'),
    ]

    operations = [
        migrations.AddField(
            model_name='db_project_list',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
